# test F1 score cal with provided GT and masks generated by suns
# explained in cal_F1.png
import os
import numpy as np
from scipy.io import loadmat

from suns.PostProcessing.evaluate import GetPerformance_Jaccard_2

def visualization(Masks):
    print(f"{Masks}.shape: {Masks.shape}")
    data_GT = Masks[:, :, 0]
    coordinates = np.where(data_GT == 1)
    print("最大值1的坐标：", list(zip(coordinates[0], coordinates[1])))
    print(data_GT)

# GT_sparse
dir_Masks_GT = "D:\PyCharm_project\SUNS_paper_reproduction\data_zq\ABO\\175\GT Masks"
filename_GT = os.path.join(dir_Masks_GT, "FinalMasks_FPremoved_501271265_sparse_generated.mat")

data_GT = loadmat(filename_GT)
GTMasks_2 = data_GT['GTMasks_2'].transpose()

# Mask_sparse
dir_Masks_output = "D:\PyCharm_project\SUNS_paper_reproduction\data_zq\output masks all methods_copied\ABO\\175\STNeuroNet FinalMasks"
filename_output = os.path.join(dir_Masks_output, "FinalSegments_501271265_sparse.mat")

data_Masks = loadmat(filename_output)
Masks_2 = data_Masks['Masks'].transpose()

# cal performance
(Recall, Precision, F1) = GetPerformance_Jaccard_2(GTMasks_2, Masks_2, ThreshJ=0.5)
print({'Recall': Recall, 'Precision': Precision, 'F1': F1})
