# test F1 score cal with provided GT and masks generated by suns
# explained in cal_F1.png
import os
from scipy.io import loadmat

from suns.PostProcessing.evaluate import GetPerformance_Jaccard_2

# GT_sparse
dir_Masks_GT = "D:\PyCharm_project\SUNS_paper_reproduction\data_zq\CaImAn dataset\YST\GT Masks"
filename_GT = os.path.join(dir_Masks_GT, "FinalMasks_YST_part11_sparse.mat")

data_GT = loadmat(filename_GT)
GTMasks_2 = data_GT['GTMasks_2'].transpose()

# Mask_sparse
dir_Masks_output = "D:\PyCharm_project\SUNS_paper_reproduction\data_zq\output masks all methods_copied\CaImAn dataset\YST\SUNS noSF output_masks"
filename_output = os.path.join(dir_Masks_output, "Output_Masks_YST_part11_sparse.mat")

data_Masks = loadmat(filename_output)
Masks_2 = data_Masks['Masks'].transpose()

# cal performance
(Recall, Precision, F1) = GetPerformance_Jaccard_2(GTMasks_2, Masks_2, ThreshJ=0.5)
print({'Recall': Recall, 'Precision': Precision, 'F1': F1})
